### ISSUE TITLE
Failed to find width and height of CSGO.

### ISSUE THREAD

**Issue by ShiedaYoung** [RealGlitchless/AI_Bot#2]
Failed to find width and height of CSGO.
How can I deal with it?
I have already set the window mode to In Window.
My title of cego is "Counter-Strike: Global Offensive Direct 3D 9" I changed the source code to satisfy this title but it still doesn't work.

**Comment by RealSoerensen** [comment]
Hello!
Sorry for the late response, I didn't receive a notification on your raised issue.
I will look into it when I get home :)
Regards

**Comment by gantanhao66** [comment]
你好 我也是这样的问题 请问怎么解决

**Comment by RealSoerensen** [comment]
I have fixed it but not release it yet as the aimbot doesn't work for some reason. I'm trying to fix it but not a priority
